-- GENRES
INSERT INTO GENRES(GENRENAME) VALUES ('ROCK');
INSERT INTO GENRES(GENRENAME) VALUES ('ALTERNATIVE ROCK');
INSERT INTO GENRES(GENRENAME) VALUES ('EXPERIMENTAL ROCK');
INSERT INTO GENRES(GENRENAME) VALUES ('FOLK ROCK');
INSERT INTO GENRES(GENRENAME) VALUES ('GARAGE ROCK');
INSERT INTO GENRES(GENRENAME) VALUES ('HARD ROCK');
INSERT INTO GENRES(GENRENAME) VALUES ('GLAM ROCK');
INSERT INTO GENRES(GENRENAME) VALUES ('HEAVY METAL');
INSERT INTO GENRES(GENRENAME) VALUES ('POP ROCK');
INSERT INTO GENRES(GENRENAME) VALUES ('PUNK ROCK');
INSERT INTO GENRES(GENRENAME) VALUES ('DISCO');
INSERT INTO GENRES(GENRENAME) VALUES ('FUNK');
INSERT INTO GENRES(GENRENAME) VALUES ('JAZZ');
INSERT INTO GENRES(GENRENAME) VALUES ('SOUL');
INSERT INTO GENRES(GENRENAME) VALUES ('POP');
INSERT INTO GENRES(GENRENAME) VALUES ('TANGO');
INSERT INTO GENRES(GENRENAME) VALUES ('LATIN');
INSERT INTO GENRES(GENRENAME) VALUES ('HIP HOP');
INSERT INTO GENRES(GENRENAME) VALUES ('REGGAE');
INSERT INTO GENRES(GENRENAME) VALUES ('RAP');
INSERT INTO GENRES(GENRENAME) VALUES ('ELECTRONIC');

-- ARTISTS
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('KIM GORDON', 64);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('MICHAEL STIPE', 57);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('DAVID BOWIE', 69);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('BOB DYLAN', 76);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('IGGY POP', 70);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('ROGER DALTREY', 73);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('RITCHIE BLACKMORE', 72);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('LADY GAGA', 31);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('JOHN LYDON', 61);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('GLORIA GAYNOR', 67);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('JAMES BROWN', 73);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('MILES DAVIS', 65);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('ARETHA FRANKLIN', 75);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('CARLOS GARDEL', 44);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('SHAKIRA', 40);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('RZA', 47);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('BOB MARLEY', 36);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('MIKE D', 51);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('CALVIN HARRIS', 33);
INSERT INTO ARTISTS(STAGENAME, AGE) VALUES('THURSTON MOORE', 58);

-- BANDS
INSERT INTO BANDS(BANDNAME) VALUES('SONIC YOUTH');
INSERT INTO BANDS(BANDNAME) VALUES('IGGY POP');
INSERT INTO BANDS(BANDNAME) VALUES('REM');
INSERT INTO BANDS(BANDNAME) VALUES('THE WHO');
INSERT INTO BANDS(BANDNAME) VALUES('BEASTIE BOYS');
INSERT INTO BANDS(BANDNAME) VALUES('THE SEX PISTOLS');
INSERT INTO BANDS(BANDNAME) VALUES('WU-TANG CLAN');
INSERT INTO BANDS(BANDNAME) VALUES('BOB DYLAN');
INSERT INTO BANDS(BANDNAME) VALUES('SHAKIRA');
INSERT INTO BANDS(BANDNAME) VALUES('DAVID BOWIE');
INSERT INTO BANDS(BANDNAME) VALUES('LADY GAGA');
INSERT INTO BANDS(BANDNAME) VALUES('MILES DAVIS');

-- BANDMEMBERS
INSERT INTO BANDMEMBERS(BANDID, ARTISTID) VALUES(1, 1);
INSERT INTO BANDMEMBERS(BANDID, ARTISTID) VALUES(2, 5);
INSERT INTO BANDMEMBERS(BANDID, ARTISTID) VALUES(3, 2);
INSERT INTO BANDMEMBERS(BANDID, ARTISTID) VALUES(4, 6);
INSERT INTO BANDMEMBERS(BANDID, ARTISTID) VALUES(5, 18);
INSERT INTO BANDMEMBERS(BANDID, ARTISTID) VALUES(6, 9);
INSERT INTO BANDMEMBERS(BANDID, ARTISTID) VALUES(7, 16);
INSERT INTO BANDMEMBERS(BANDID, ARTISTID) VALUES(8, 4);
INSERT INTO BANDMEMBERS(BANDID, ARTISTID) VALUES(9, 15);
INSERT INTO BANDMEMBERS(BANDID, ARTISTID) VALUES(10, 3);
INSERT INTO BANDMEMBERS(BANDID, ARTISTID) VALUES(11, 8);
INSERT INTO BANDMEMBERS(BANDID, ARTISTID) VALUES(12, 12);
INSERT INTO BANDMEMBERS(BANDID, ARTISTID) VALUES(1, 20);

-- ALBUMS
INSERT INTO ALBUMS(ALBUMNAME, AUTHOR, GENRE, RELEASEYEAR, DURATION) VALUES('Green', 3, 2, 1988, 41);
INSERT INTO ALBUMS(ALBUMNAME, AUTHOR, GENRE, RELEASEYEAR, DURATION) VALUES('The Rise and Fall of Ziggy Stardust and the Spiders from Mars', 10, 7, 1972, 39);
INSERT INTO ALBUMS(ALBUMNAME, AUTHOR, GENRE, RELEASEYEAR, DURATION) VALUES('Lust for Life', 2, 6, 1977, 42);
INSERT INTO ALBUMS(ALBUMNAME, AUTHOR, GENRE, RELEASEYEAR, DURATION) VALUES('Born This Way', 11, 15, 1977, 62);
INSERT INTO ALBUMS(ALBUMNAME, AUTHOR, GENRE, RELEASEYEAR, DURATION) VALUES('Kind of Blue', 12, 13, 1959, 62);
